### ISSUE TITLE
Doesn't work with the latest compass

### ISSUE THREAD

**Issue by r007** [staticmatic/staticmatic#25]
``` ruby
c:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-0.12.1/lib/compass/app_integration.rb:27:in `lookup': No application integration exists for staticmatic (Compass::Error)
    from c:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-0.12.1/lib/compass/configuration/helpers.rb:44:in `configuration_for'
    from c:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-0.12.1/lib/compass/configuration/helpers.rb:22:in `add_configuration'
    from c:/Ruby193/lib/ruby/gems/1.9.1/gems/staticmatic-0.11.1/lib/staticmatic/compass.rb:5:in `<top (required)>'
    from c:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from c:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from c:/Ruby193/lib/ruby/gems/1.9.1/gems/staticmatic-0.11.1/lib/staticmatic.rb:21:in `block in <top (required)>'
    from c:/Ruby193/lib/ruby/gems/1.9.1/gems/staticmatic-0.11.1/lib/staticmatic.rb:20:in `each'
    from c:/Ruby193/lib/ruby/gems/1.9.1/gems/staticmatic-0.11.1/lib/staticmatic.rb:20:in `<top (required)>'
    from c:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from c:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from c:/Ruby193/lib/ruby/gems/1.9.1/gems/staticmatic-0.11.1/bin/staticmatic:3:in `<top (required)>'
    from c:/Ruby193/bin/staticmatic:19:in `load'
    from c:/Ruby193/bin/staticmatic:19:in `<main>'
```

Any ideas?

**Comment by erotte** [comment]
+1

**Comment by stevebartholomew** [comment]
Sorry, staticmatic is no longer in development - I suggest you try middleman: http://middlemanapp.com.

I'll get the repository updated to make this clear,

**Comment by bnugman** [comment]
FYI, made it work by uninstalling all versions of compass and then 

gem install compass -v 0.11.7
